version: '3'
services:
#################################################################


#################################################################

  tomcat:
    image: docker.io/bitnami/tomcat:9.0
    privileged: true
    user: root
    ports:
      - 8888:8080
    container_name: tomcat
    volumes:
      - ~/tomcat:/bitnami/tomcat'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
