version: '3'
services:
#################################################################

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - docker_network

#ensure the directory ~/jenkins exists

#################################################################

  tomcat:
    image: docker.io/bitnami/tomcat:9.0
    privileged: true
    user: root
    ports:
      - 8880:8080
    container_name: tomcat
    volumes:
      - ~/tomcat:/bitnami/tomcat'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - docker_network

#################################################################

  postgresql:
    image: docker.io/bitnami/postgresql:13
    privileged: true
    user: root
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
      
#################################################################     
      
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    privileged: true
    user: root
    ports:
      - 80:9000
    container_name: sonarqube
    volumes:
      - sonarqube_data:/bitnami/sonarqube
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
    networks:
      - docker_network

#################################################################

  nexus:
    image: sonatype/nexus3
    privileged: true
    user: root
    container_name: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    networks:
      - docker_network
      
#################################################################
  
  chrome:
    image: selenium/node-chrome:4.1.1-20211217
    privileged: true
    user: root
    container_name: selenium_node_chrom
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - docker_network

  firefox:
    image: selenium/node-firefox:4.1.1-20211217
    privileged: true
    user: root
    container_name: selenium_node_firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - docker_network

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    privileged: true
    user: root
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - docker_network
      
#################################################################



volumes:
  tomcat_data:
                driver: local
  postgresql_data:
                driver: local
  sonarqube_data:
                driver: local
  nexus-data: {}
               
networks:
    docker_network:
        driver: bridge

