version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - docker_network

services:
  tomcat:
    image: docker.io/bitnami/tomcat:9.0
    privileged: true
    user: root
    ports:
      - 8880:8080
    container_name: tomcat
    volumes:
      - ~/tomcat:/bitnami/tomcat'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - docker_network
    volumes:
        tomcat_data:
                driver: local
    networks:
      - docker_network

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    privileged: true
    user: root
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    privileged: true
    user: root
    ports:
      - 80:9000
    volumes:
      - sonarqube_data:/bitnami/sonarqube
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube

volumes:
     postgresql_data:
                 driver: local
     sonarqube_data:
                 driver: local


networks:
    docker_network:
        driver: bridge


[vagrant@JeanneBM ~]$

